### ISSUE TITLE
Document/attachment boundary issue in frus1865p1

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/frus#252]
As reported by @seckroth:

> I noticed that we have some problems with document divisions within frus1865p1. I remember these not having standard headings and the vendor having difficulties distinguishing between attachments/enclosures and new documents. The example I was working on is:
> 
> https://history.state.gov/historicaldocuments/frus1865p1/d373
>
> I think I counted 8 individual documents (2 with enclosures) that should have their own document numbers tagged as frus:attachment in d373. 

@vak2ve Could you please take a look at this and start a branch for these changes?  If any “documents” are reclassified as attachments, please move them, and of course, please do not renumber documents after such changes.  For example, if you reclassify document 9 as an attachment belonging to document 8, document 10 will remain as document 10 (not renumbered as document 9), etc.  After making these changes so you may see Schematron warnings about skips in the document number sequence, so just ignore these because of this special case.  

Besides committing this work into a branch, could you send me a report of which documents you reclassify as attachments, and the new parent document for these moved/reclassified attachments?  Before I merge your changes I'd like to prepare (a) an errata statement with @machalou and ideally (b) some kind of redirect facility so requests to the documents are redirected to the new location of the attachment.

**Comment by vak2ve** [comment]
@joewiz On it!

**Comment by vak2ve** [comment]
@joewiz and @seckroth Looking at d373 I see one attachment that should be its own document--a new document div should start at No. 1586.], on page 659. (I think I was thrown off by the [Enclosure] below its heading, which maybe belongs to the Hibbard to Seward attachment below?) 

The remaining difficulties with d373 are on my end though, since the nesting of the main document and its attachments (and their attachments) looks right to me. From the context of the main document  (Seward to Adams) it seems as though Seward was transmitting a package of related documents from various authors, often with their own related documents, on a consistent subject (in this case the _Shenandoah_). I treated this package as one document because I assumed it would have arrived as such, and its component parts refer to each other in a logical sequential order--Seward to Adams transmits Galody to Seward which transmits Murray's letter of the 16th and the Cardwell's circular of the 7th, etc. Did I miss something here?

**Comment by seckroth** [comment]
I think I see where I made my mistake! I think there is an OCR error in the document number (No. 1085 should be No. 1585). I was looking at the TOC starting a couple of docs above it at 1085 instead of 1585 and thought there must be more

**Comment by vak2ve** [comment]
Your mistake revealed mine so thank you! Some of these nested document packages were _very_ convoluted so I appreciate the second pair of eyes!
